// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gizomguhcjomeydclezp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdpem9tZ3VoY2pvbWV5ZGNsZXpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMDMxNzAsImV4cCI6MjA2NzY3OTE3MH0.jOSTidy8dbU69P8qv25XJ96e6-usj_UjcxI2J65epSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});